spring:
   datasource:
      username: online_store
      password: online_store
      url: jdbc:mysql://localhost:3306/online_store
   
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      defer-datasource-initialization: true
      
         

   
   